context:
  version: "1.22.6"

package:
  name: ed
  version: ${{ version }}

source:
  url: https://ftp.gnu.org/gnu/ed/ed-${{ version }}.tar.lz
  sha256: 3f33b22135219c39c3c695f7b7171c2567d3e2a17c798c0a90607320cbb268f2
  file_name: ed-${{ version }}.tar.lz

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - lzip
    - make

tests:
  - script:
      - ed --help

about:
  license: GPL-3.0-or-later
  license_file: ed-${{ version }}/COPYING
  summary: Classic UNIX line editor
  homepage: https://www.gnu.org/software/ed

extra:
  recipe-maintainers:
    - danielnachun
